### PR TITLE
Fix ToggleInput keybind issue

### PR DESCRIPTION
**Pull request by focusright**
Issue fixed based on this [discussion](https://github.com/IDI-Systems/UnrealImGui/issues/13).

### CODE REVIEW

**Comment by jonpas** [comment]
`EnhancedInput` is experimental in UE4. Although maybe it is time to drop UE4 support in this project.

**Comment by focusright** [comment]
EnhancedInput is on by default for UE 5.3, the fix is only meant for that.

**Comment by jonpas** [comment]
This plugin currently supports engine versions from 4.26 to 5.3. This essentially enables an experimental feature in 4.x, which I am not a fan of.

**Comment by focusright** [comment]
Perhaps git tags can come to the rescue here?

**Comment by jonpas** [comment]
I don't particularly want to diverge into UE4 and UE5 versions, it would take a larger community to support that well enough. I will most likely tag the last version that fully supports UE4 and then drop it from that point onwards. This of course does not stop anyone from updating the UE4 version.

**Comment by focusright** [comment]
That makes sense, thanks.

**Comment by jonpas** [comment]
Replaced by #22. Thank you anywys!

**Pull request closed without merging**
